#
# Travis CI Repo options for this pipeline:
#
#   Travis CI Env Var      Type      Notes
#   ---------------------  --------  -------------------------------------------
#   GITHUB_OAUTH_TOKEN     Secure    Required for automated GitHub releases
#   SKIP_GITHUB_PUBLISH    Optional  Skips publishing GitHub releases if "true"
#
#   The secure env vars will be filtered in Travis CI log output, and aren't
#   provided to untrusted builds (i.e, triggered by PR from another repository)
#
# ------------------------------------------------------------------------------
#
# Travis CI Trigger options for this pipeline:
#
#   To validate if $GITHUB_OAUTH_TOKEN is able to publish a GitHub release,
#   trigger a custom Travis CI build for this branch using the CUSTOM CONFIG:
#
#     env: VALIDATE_TOKENS=yes
#
# ------------------------------------------------------------------------------
#
# Release Engineering notes:
#
#   To automagically publish a release to GitHub:
#
#   - Set GITHUB_OAUTH_TOKEN as secure env variables
#     in this repo's Travis CI settings
#   - Push a git tag that matches the version in the component's
#     `build/<component>.spec`
#   - The tag SHOULD be annotated with release notes, but nothing enforces this
#     convention at present
#
# ------------------------------------------------------------------------------
---

language: shell
version: ~> 1.0
os: linux

notifications:
  email: false

addons:
  apt:
    packages:
      - rpm
env:
  global:
    - 'FORGE_USER_AGENT="TravisCI-ForgeReleng-Script/0.3.3 (Purpose/forge-ops-for-${TRAVIS_REPO_SLUG})"'

stages:
  - name: 'validate tokens'
    if: 'env(VALIDATE_TOKENS) = yes'
  - name: deploy
    if: 'tag IS present AND NOT env(VALIDATE_TOKENS) = yes'
    ###
    ###  Testing on Travis CI is indefinitely disabled
    ###
    ###  See:
    ###    * https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing
    ###    * https://simp-project.atlassian.net/browse/SIMP-8703
    ###
    ###  - name: check
    ###    if: 'NOT env(VALIDATE_TOKENS) = yes'
    ###  - name: spec
    ###    if: 'NOT env(VALIDATE_TOKENS) = yes'

jobs:
  include:

    - stage: deploy
      rvm: 2.4.9
      env: PUPPET_VERSION="~> 5.5.0"
      script:
        - true
      before_deploy:
        - "export SPECFILE_VERSION=`rpm -q --specfile build/*.spec --queryformat '%{VERSION}'`"
        - '[[ $TRAVIS_TAG =~ ^${SPECFILE_VERSION}$ ]]'
      deploy:
        - provider: releases
          token: $GITHUB_OAUTH_TOKEN
          on:
            tags: true
            condition: '($SKIP_GITHUB_PUBLISH != true)'

    - stage: 'validate tokens'
      language: shell
      before_install: skip
      install: skip
      name:  'validate CI GitHub OAuth token has sufficient scope to release'
      script:
      - 'echo; echo "===== GITHUB_OAUTH_TOKEN validation";echo "  (TRAVIS_SECURE_ENV_VARS=$TRAVIS_SECURE_ENV_VARS)"; echo'
      - 'OWNER="$(echo $TRAVIS_REPO_SLUG | cut -d/ -f1)"'
      - 'curl -H "Authorization: token ${GITHUB_OAUTH_TOKEN}"
          "https://api.github.com/users/$OWNER"
          -I | grep ^X-OAuth-Scopes | egrep -w "repo|public_repo"'
